service: indra-aws-node-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  getPeopleFromSwapi:
    handler: index.getPeopleFromSwapi
    events:
      - httpApi:
          path: /sw/personaje/{id}
          method: GET
  getBicycle:
    handler: index.getBicycle
    events:
      - httpApi:
          path: /producto/{id}
          method: GET
  saveBicycle:
    handler: index.saveBicycle
    events:
      - httpApi:
          path: /producto
          method: POST
custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.json'
plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-jest-plugin
  - serverless-offline